using System;
using System.ComponentModel;

namespace SAMaster.Entities
{
	/// <summary>
	///		The data structure representation of the 'mst_links_ac' table via interface.
	/// </summary>
	/// <remarks>
	/// 	This struct is generated by a tool and should never be modified.
	/// </remarks>
	public interface IMstLinksAc 
	{
		/// <summary>			
		/// MAPINFO_ID : 
		/// </summary>
		/// <remarks>Member of the primary key of the underlying table "mst_links_ac"</remarks>
		System.Int32 MapinfoId { get; set; }
				
		/// <summary>
		/// keep a copy of the original so it can be used for editable primary keys.
		/// </summary>
		System.Int32 OriginalMapinfoId { get; set; }
			
		
		
		/// <summary>
		/// MLinkID : 
		/// </summary>
		System.Int32?  MlinkId  { get; set; }
		
		/// <summary>
		/// CompKey : 
		/// </summary>
		System.Int32?  CompKey  { get; set; }
		
		/// <summary>
		/// USNode : 
		/// </summary>
		System.String  UsNode  { get; set; }
		
		/// <summary>
		/// DSNode : 
		/// </summary>
		System.String  DsNode  { get; set; }
		
		/// <summary>
		/// PipeShape : 
		/// </summary>
		System.String  PipeShape  { get; set; }
		
		/// <summary>
		/// LinkType : 
		/// </summary>
		System.String  LinkType  { get; set; }
		
		/// <summary>
		/// PipeFlowType : 
		/// </summary>
		System.String  PipeFlowType  { get; set; }
		
		/// <summary>
		/// Length : 
		/// </summary>
		System.Double?  Length  { get; set; }
		
		/// <summary>
		/// DiamWidth : 
		/// </summary>
		System.Double?  DiamWidth  { get; set; }
		
		/// <summary>
		/// Height : 
		/// </summary>
		System.Double?  Height  { get; set; }
		
		/// <summary>
		/// Material : 
		/// </summary>
		System.String  Material  { get; set; }
		
		/// <summary>
		/// upsdpth : 
		/// </summary>
		System.Double?  Upsdpth  { get; set; }
		
		/// <summary>
		/// dwndpth : 
		/// </summary>
		System.Double?  Dwndpth  { get; set; }
		
		/// <summary>
		/// USIE : 
		/// </summary>
		System.Double?  Usie  { get; set; }
		
		/// <summary>
		/// DSIE : 
		/// </summary>
		System.Double?  Dsie  { get; set; }
		
		/// <summary>
		/// AsBuilt : 
		/// </summary>
		System.String  AsBuilt  { get; set; }
		
		/// <summary>
		/// Instdate : 
		/// </summary>
		System.DateTime?  Instdate  { get; set; }
		
		/// <summary>
		/// FromX : 
		/// </summary>
		System.Double?  Fromx  { get; set; }
		
		/// <summary>
		/// FromY : 
		/// </summary>
		System.Double?  Fromy  { get; set; }
		
		/// <summary>
		/// ToX : 
		/// </summary>
		System.Double?  Tox  { get; set; }
		
		/// <summary>
		/// ToY : 
		/// </summary>
		System.Double?  Toy  { get; set; }
		
		/// <summary>
		/// Roughness : 
		/// </summary>
		System.Double?  Roughness  { get; set; }
		
		/// <summary>
		/// TimeFrame : 
		/// </summary>
		System.String  TimeFrame  { get; set; }
		
		/// <summary>
		/// DataFlagSynth : 
		/// </summary>
		System.Int32?  DataFlagSynth  { get; set; }
		
		/// <summary>
		/// DataQual : 
		/// </summary>
		System.String  DataQual  { get; set; }
		
		/// <summary>
		/// Hservstat : 
		/// </summary>
		System.String  Hservstat  { get; set; }
		
		/// <summary>
		/// ValidFromDate : 
		/// </summary>
		System.String  ValidFromDate  { get; set; }
		
		/// <summary>
		/// ValidToDate : 
		/// </summary>
		System.String  ValidToDate  { get; set; }
		
		/// <summary>
		/// CADKey : 
		/// </summary>
		System.String  CadKey  { get; set; }
		
		/// <summary>
		/// AuditNodeID : 
		/// </summary>
		System.String  AuditNodeId  { get; set; }
		
		/// <summary>
		/// AuditDups : 
		/// </summary>
		System.String  AuditDups  { get; set; }
		
		/// <summary>
		/// AuditSpatial : 
		/// </summary>
		System.String  AuditSpatial  { get; set; }
		
		/// <summary>
		/// AuditOK2Go : 
		/// </summary>
		System.Boolean  AuditOk2Go  { get; set; }
		
		/// <summary>
		/// AuditProcTimestamp : 
		/// </summary>
		System.String  AuditProcTimestamp  { get; set; }
		
		/// <summary>
		/// Qdes : 
		/// </summary>
		System.Double?  Qdes  { get; set; }
		
		/// <summary>
		/// DME_GlobalID : 
		/// </summary>
		System.Int32?  DmeGlobalId  { get; set; }
			
		/// <summary>
		/// Creates a new object that is a copy of the current instance.
		/// </summary>
		/// <returns>A new object that is a copy of this instance.</returns>
		System.Object Clone();
		
		#region Data Properties

		#endregion Data Properties

	}
}


